name: fitform_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image: ^4.0.17
  # Camera & ML Kit - Hum specific, compatible versions use kar rahe hain
  camera: ^0.10.5+5
  google_mlkit_pose_detection: 0.10.0
  google_mlkit_commons: 0.6.0

  # Audio
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0

  # UI Packages
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  lottie: ^3.3.1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

# Yeh Flutter ko majboor karega ki woh in packages ke yahi versions use kare,
# taaki koi conflict na ho. Yeh native crash ko solve karega.
dependency_overrides:
  google_mlkit_commons: 0.6.0

flutter:
  uses-material-design: true

  # Saare asset folders ko is tarah register karna best practice hai.
  # Isse aapko har nayi image ke liye file me aane ki zaroorat nahi padegi.
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/deep_learning/gym_pose_model.tflite
    - assets/deep_learning/labels.txt

# Yeh section alag, file ke end me hona chahiye.
flutter_native_splash:
  color: "#1A1A2E"
  image: assets/logo/App_Logo.png

  android_12:
    color: "#1A1A2E"
    image: assets/logo/App_Logo.png